version: '3.9'

services:
  web:
    build:
      context: https://github.com/panda1312/Scriptura.git
      dockerfile: docker/web/Dockerfile
    container_name: dbman
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - SECRET_KEY=devsecretkey
    volumes:
      - ./app:/app/app
      - ./run.py:/app/run.py
    depends_on:
      - db
    networks:
      - sql-manager-network

  db:
    image: postgres:15
    container_name: sql-manager-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sql-manager-network

volumes:
  db-data:

networks:
  sql-manager-network:
    driver: bridge
