version: '3.9'

services:
  web:
    build: https://github.com/panda1312/DBMan.git
    container_name: dbman
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - sql-manager-network

  db:
    image: postgres:15
    container_name: sql-manager-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepassword  # Change this!
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sql-manager-network

volumes:
  db-data:

networks:
  sql-manager-network:
    driver: bridge
